name: keylol action
on:
  schedule:
    - cron: "* * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Keylol Action
        uses: yuyinws/keylol-action@v1.1
        with:
          urls: 
            forum.php?mod=forumdisplay&fid=234&filter=author&orderby=dateline&typeid=529
            forum.php?mod=forumdisplay&fid=161&filter=typeid&typeid=458&orderby=dateline
            forum.php?mod=forumdisplay&fid=251&orderby=dateline&filter=dateline&orderby=dateline&typeid=765           
          limit: 10

      - name: Send mail
        uses: dawidd6/action-send-mail@v3.6.0
        with:
          # smtp 服务器地址
          server_address: smtp.qq.com
          # smtp 服务器端口
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: 龙心爱你呦（づ￣3￣）づ╭❤～
          html_body: file://context.html
          to: ${{ secrets.TARGET_MAIL }}
          from: 龙心爱你呦（づ￣3￣）づ╭❤～
          convert_markdown: true
